version: "3"

services:
  mysql:
      image: mysql:5.7.20
      ports:
          - "33061:3306"
      volumes:
          - ./../dbdata:/var/lib/mysql
          - /etc/localtime:/etc/localtime
      environment:
          - "MYSQL_ROOT_PASSWORD=123456"
          - "MYSQL_DATABASE=kuncie"